#ifndef MYDATABASEUTIL_GLOBAL_H
#define MYDATABASEUTIL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MYDATABASEUTIL_LIBRARY)
#  define MYDATABASEUTILSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MYDATABASEUTILSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MYDATABASEUTIL_GLOBAL_H
